version: '3'

services:
  appointments_service:
    image: salissalman/appointments-service:0a6bf1cf63fbd46a0cfbc4624695be9b4941f930
    ports:
      - "7070:7070"
    networks:
      - backend_network

  doctors_service:
    image: salissalman/doctors-service:c241dc8304a9f578e507b375a26e7c7df9a08119
    ports:
      - "9090:9090"
    networks:
      - backend_network

  frontend_service:
    image: salissalman/frontend-service:e5b15ed8b6b3a368e974d9cbd41653bc629805fa
    ports:
      - "3000:3000"
    networks:
      - backend_network
    environment:
      - DOCTORS_SERVICE_URL=doctors_service:9090
      - APPOINTMENTS_SERVICE_URL=appointments_service:7070

networks:
  backend_network:
