version: '3'

services:
  appointments_service:
    image: salissalman/appointments-service:91ff2f434c77f83fe8e6aff3e0b6ce10c4008742
    ports:
      - "7070:7070"
    networks:
      - backend_network

  doctors_service:
    image: salissalman/doctors-service:dd4e9340fd4dce6b45f6fe7643442aad54615697
    ports:
      - "9090:9090"
    networks:
      - backend_network

  frontend_service:
    image: salissalman/frontend-service:91ff2f434c77f83fe8e6aff3e0b6ce10c4008742
    ports:
      - "3000:3000"
    networks:
      - backend_network
    environment:
      - DOCTORS_SERVICE_URL=doctors_service:9090
      - APPOINTMENTS_SERVICE_URL=appointments_service:7070

networks:
  backend_network:
