version: '3'

services:
  appointments_service:
    image: salissalman/appointments-service:2b9309a2982fc8be0ad720d3cc42446d3ba10117
    ports:
      - "7070:7070"
    networks:
      - backend_network

  doctors_service:
    image: salissalman/doctors-service:63dc8111f361a4c23cf4808a608e692765cfb457
    ports:
      - "9090:9090"
    networks:
      - backend_network

  frontend_service:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - backend_network
    environment:
      - DOCTORS_SERVICE_URL=doctors_service:9090
      - APPOINTMENTS_SERVICE_URL=appointments_service:7070

networks:
  backend_network:
