version: '3'

services:
  appointments_service:
    image: salissalman/appointments-service:0a6bf1cf63fbd46a0cfbc4624695be9b4941f930
    ports:
      - "7070:7070"
    networks:
      - backend_network

  doctors_service:
    image: salissalman/doctors-service:168c65e47f4ef099811cc52bcd30642b7f2267c0
    ports:
      - "9090:9090"
    networks:
      - backend_network

  frontend_service:
    image: salissalman/frontend-service:04e17bd52ae00ea445a1200f961d7876c6c2f833
    ports:
      - "3000:3000"
    networks:
      - backend_network
    environment:
      - DOCTORS_SERVICE_URL=doctors_service:9090
      - APPOINTMENTS_SERVICE_URL=appointments_service:7070

networks:
  backend_network:
