version: '3'

services:
  appointments_service:
    image: salissalman/appointments-service:2b9309a2982fc8be0ad720d3cc42446d3ba10117
    ports:
      - "7070:7070"
    networks:
      - backend_network

  doctors_service:
    image: salissalman/doctors-service:31e23dc67412ed60e1acb8c5e263879c7f98ff3e
    ports:
      - "9090:9090"
    networks:
      - backend_network

  frontend_service:
    image: salissalman/frontend-service:e5b15ed8b6b3a368e974d9cbd41653bc629805fa
    ports:
      - "3000:3000"
    networks:
      - backend_network
    environment:
      - DOCTORS_SERVICE_URL=doctors_service:9090
      - APPOINTMENTS_SERVICE_URL=appointments_service:7070

networks:
  backend_network:
