version: '3'

services:
  appointments_service:
    image: salissalman/appointments-service:07eb282eb9f0cd529a46e997269f55d4df77b5a3
    ports:
      - "7070:7070"
    networks:
      - backend_network

  doctors_service:
    image: salissalman/doctors-service:8ecefc1ec463f5a7eb07f13a63afda2383f4c6d2
    ports:
      - "9090:9090"
    networks:
      - backend_network

  frontend_service:
    image: salissalman/frontend-service:e550ee5546c80c854f98482c6830101048445437
    ports:
      - "3000:3000"
    networks:
      - backend_network
    environment:
      - DOCTORS_SERVICE_URL=doctors_service:9090
      - APPOINTMENTS_SERVICE_URL=appointments_service:7070

networks:
  backend_network:
