version: '3'

services:
  appointments_service:
    image: salissalman/appointments-service:1a68f3fe012fe9f611f935895cff892816265d1e
    ports:
      - "7070:7070"
    networks:
      - backend_network

  doctors_service:
    image: salissalman/doctors-service:c5caafdd59fe7f53225e8dd2c159501ee29b29c8
    ports:
      - "9090:9090"
    networks:
      - backend_network

  frontend_service:
    image: salissalman/frontend-service:c5caafdd59fe7f53225e8dd2c159501ee29b29c8
    ports:
      - "3000:3000"
    networks:
      - backend_network
    environment:
      - DOCTORS_SERVICE_URL=doctors_service:9090
      - APPOINTMENTS_SERVICE_URL=appointments_service:7070

networks:
  backend_network:
