version: '3'

services:
  appointments_service:
    image: salissalman/appointments-service:c7464968de05c7b32729efc35bcda217bd7f5264
    ports:
      - "7070:7070"
    networks:
      - backend_network

  doctors_service:
    image: salissalman/doctors-service:9e46d067c582a59df6dd573ffd1e26e5932e0164
    ports:
      - "9090:9090"
    networks:
      - backend_network

  frontend_service:
    image: salissalman/frontend-service:e5b15ed8b6b3a368e974d9cbd41653bc629805fa
    ports:
      - "3000:3000"
    networks:
      - backend_network
    environment:
      - DOCTORS_SERVICE_URL=doctors_service:9090
      - APPOINTMENTS_SERVICE_URL=appointments_service:7070

networks:
  backend_network:
