---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointments-deployment
spec:
  selector:
    matchLabels:
      tier: backend
      app: microservices
  template:
    metadata:
      labels:
        tier: backend
        app: microservices
    spec:
      containers:
      - name: appointments-service
        image: salissalman/appointments-service:2b9309a2982fc8be0ad720d3cc42446d3ba10117
        ports:
        - containerPort: 7070
---
apiVersion: v1
kind: Service
metadata:
  name: appointments-service
spec:
  selector:
    tier: backend
    app: microservices
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070