apiVersion: v1
kind: Service
metadata:
  name: appointments-service
spec:
  selector:
    app: appointments-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7070

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointments-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointments-service
  template:
    metadata:
      labels:
        app: appointments-service
    spec:
      containers:
        - name: appointments-service
          image: salissalman/appointments-service:2b9309a2982fc8be0ad720d3cc42446d3ba10117
          ports:
            - containerPort: 7070