apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-2
spec:
  selector:
    matchLabels:
      tier: frontend
      app: microservices
  template:
    metadata:
      labels:
        tier: frontend
        app: microservices      
    spec:
      containers:
        - name: frontend-service
          image: salissalman/frontend-service:c5caafdd59fe7f53225e8dd2c159501ee29b29c8
          ports:
            - containerPort: 3000
          env:
            - name: DOCTORS_SERVICE_URL
              value: doctors-service:9090
            - name: APPOINTMENTS_SERVICE_URL
              value: appointments-service:7070
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    tier: frontend
    app: microservices
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001