apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctors-deployment
spec:
  selector:
    matchLabels:
      tier: backend
      app: microservices
  template:
    metadata:
      labels:
        tier: backend
        app: microservices
    spec:
      containers:
        - name: doctors-service
          image: salissalman/doctors-service:31e23dc67412ed60e1acb8c5e263879c7f98ff3e
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: doctors-service
spec:
  selector:
    tier: backend
    app: microservices
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      