apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctors-deployment
spec:
  selector:
    matchLabels:
      tier: backend
      app: microservices
  template:
    metadata:
      labels:
        tier: backend
        app: microservices
    spec:
      containers:
        - name: doctors-service
          image: salissalman/doctors-service:4ae8409b7058a54cc15f71d441589a3d03898462
          ports:
            - containerPort: 9090
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: doctors-service
spec:
  selector:
    tier: backend
    app: microservices
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30002
  type: NodePort