name: Appointments Service CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'appointments/**'
  pull_request:
    paths:
      - 'appointments/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: docker build -t salissalman/appointments-service:${{ github.sha }} ./appointments
        
      - name: Push
        run: docker push salissalman/appointments-service:${{ github.sha }}


      - name: Update Docker Compose
        run: |
          sed -i "s|image: salissalman/appointments-service:[0-9a-f]\+|image: salissalman/appointments-service:${{ github.sha }}|" docker-compose.yml

      - name: Login to Git add, commit and push
        uses: actions/checkout@v2
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Update docker-compose.yml"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.AUTH_TOKEN }}
          branch: main

        
        

          
        

          
        
          
