name: Appointments Service CI/CD

on:
  push:
    paths:
      - 'appointments/**'
    branches:
      - main
  pull_request:
    paths:
      - 'appointments/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: docker build -t salissalman/appointments-service:${{ github.sha }} ./appointments
        
      - name: Push
        run: docker push salissalman/appointments-service:${{ github.sha }}
