name: Appointments Service CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'appointments/**'
  pull_request:
    paths:
      - 'appointments/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: docker build -t salissalman/appointments-service:${{ github.sha }} ./appointments
        
      - name: Push
        run: docker push salissalman/appointments-service:${{ github.sha }}


      - name: Update Docker Compose
        run: |
          sed -i "s|image: salissalman/appointments-service:[0-9a-f]\+|image: salissalman/appointments-service:${{ github.sha }}|" docker-compose.yml

      - name: Set up Git
        run: |
          git config --global user.name "salissalmann"
          git config --global user.email "i200489@nu.edu.pk"
          git remote set-url origin "https://${{ secrets.AUTH_TOKEN }}@github.com/${{ github.repository }}.git"

      - name: Commit and Push Changes
        run: |
          git add docker-compose.yml
          git commit -m "Update appointments-service image tag to ${{ github.sha }}"
          git push origin HEAD:main