name: Doctors Service CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'doctors/**'
  pull_request:
    paths:
      - 'doctors/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: docker build -t salissalman/doctors-service:${{ github.sha }} ./doctors
        
      - name: Push
        run: docker push salissalman/doctors-service:${{ github.sha }}
