name: Doctors Service CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'doctors/**'
  pull_request:
    paths:
      - 'doctors/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: docker build -t salissalman/doctors-service:${{ github.sha }} ./doctors
        
      - name: Push
        run: docker push salissalman/doctors-service:${{ github.sha }}

      - name: Update Image on Docker Compose
        run: |
          sed -i "s|image: salissalman/doctors-service:[0-9a-f]\+|image: salissalman/doctors-service:${{ github.sha }}|" docker-compose.yml

      - name: Commit and Push Changes
        run: |        
          git config --global user.email ${{ secrets.GH_EMAIL }}
          git config --global user.name ${{ secrets.GH_NAME }}
          git config --local user.password "${{ secrets.GITHUB_TOKEN }}"
          git fetch origin main
          git add .
          git commit -m "Update docker-compose.yml By Doctors Service CI/CD"
          git push origin main